"""add family_income_log_id to personal_income_logs

Revision ID: 76cbbb02fded
Revises: ddd810043e76
Create Date: 2026-06-27 13:44:19.821145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76cbbb02fded'
down_revision: Union[str, Sequence[str], None] = 'ddd810043e76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_income_logs', sa.Column('family_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('personal_income_logs', sa.Column('family_income_log_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'personal_income_logs', 'family_income_logs', ['family_income_log_id'], ['id'])
    op.drop_column('personal_income_logs', 'personal_savings_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_income_logs', sa.Column('personal_savings_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'personal_income_logs', type_='foreignkey')
    op.drop_column('personal_income_logs', 'family_income_log_id')
    op.drop_column('personal_income_logs', 'family_amount')
    # ### end Alembic commands ###
