"""add_debt_emi_interval_columns

Revision ID: 77b34f5551ca
Revises: f2v24paymentsplituserid
Create Date: 2026-07-12 16:02:34.707277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '77b34f5551ca'
down_revision: Union[str, Sequence[str], None] = 'f2v24paymentsplituserid'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bounced_payments_debt_scope_debt_id_period_key_key'), 'bounced_payments', type_='unique')
    op.drop_index(op.f('ix_currency_rates_pair'), table_name='currency_rates')
    op.drop_index(op.f('ix_currency_rates_status'), table_name='currency_rates')
    op.drop_index(op.f('ix_debt_payment_allocations_event_id'), table_name='debt_payment_allocations')
    op.create_index(op.f('ix_debt_payment_allocations_payment_event_id'), 'debt_payment_allocations', ['payment_event_id'], unique=False)
    op.drop_index(op.f('ix_debt_payment_events_period_key'), table_name='debt_payment_events')
    op.drop_constraint(op.f('uq_debt_scope_views_target'), 'debt_scope_views', type_='unique')
    op.add_column('debts', sa.Column('emi_interval_days', sa.Integer(), nullable=True))
    op.add_column('debts', sa.Column('emi_interval_months', sa.Integer(), nullable=True))
    op.add_column('debts', sa.Column('emi_interval_years', sa.Integer(), nullable=True))
    op.alter_column('default_bucket_entries', 'settled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('ix_default_bucket_entity_id'), table_name='default_bucket_entries')
    op.drop_index(op.f('ix_default_bucket_family_id'), table_name='default_bucket_entries')
    op.drop_index(op.f('ix_default_bucket_user_id'), table_name='default_bucket_entries')
    op.create_index(op.f('ix_default_bucket_entries_entity_id'), 'default_bucket_entries', ['entity_id'], unique=False)
    op.create_index(op.f('ix_default_bucket_entries_family_id'), 'default_bucket_entries', ['family_id'], unique=False)
    op.create_index(op.f('ix_default_bucket_entries_user_id'), 'default_bucket_entries', ['user_id'], unique=False)
    op.alter_column('family_assets', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_family_assets_family_id'), 'family_assets', ['family_id'], unique=False)
    op.add_column('family_debts', sa.Column('emi_interval_days', sa.Integer(), nullable=True))
    op.add_column('family_debts', sa.Column('emi_interval_months', sa.Integer(), nullable=True))
    op.add_column('family_debts', sa.Column('emi_interval_years', sa.Integer(), nullable=True))
    op.alter_column('family_debts', 'next_interest_increase_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('family_debts', 'emi_next_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('family_debts', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('family_debts', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_column('family_debts', 'has_installments')
    op.drop_column('family_debts', 'monthly_emi')
    op.drop_column('family_debts', 'installments_every')
    op.add_column('family_goal_contributions', sa.Column('note', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'family_insurances', 'users', ['insured_user_id'], ['id'])
    op.drop_index(op.f('ix_funding_breakdown_entity_id'), table_name='funding_breakdown_entries')
    op.drop_index(op.f('ix_funding_breakdown_job_id'), table_name='funding_breakdown_entries')
    op.create_index(op.f('ix_funding_breakdown_entries_entity_id'), 'funding_breakdown_entries', ['entity_id'], unique=False)
    op.create_index(op.f('ix_funding_breakdown_entries_job_id'), 'funding_breakdown_entries', ['job_id'], unique=False)
    op.alter_column('investment_txns', 'note',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_investment_txns_investment_scope'), table_name='investment_txns')
    op.alter_column('notifications', 'actioned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('notifications', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('ix_payment_split_plans_entity'), table_name='payment_split_plans')
    op.add_column('personal_assets', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.alter_column('personal_assets', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_personal_assets_family_id'), 'personal_assets', ['family_id'], unique=False)
    op.create_index(op.f('ix_personal_assets_user_id'), 'personal_assets', ['user_id'], unique=False)
    op.drop_constraint(op.f('personal_assets_in_someone_name_fkey'), 'personal_assets', type_='foreignkey')
    op.create_foreign_key(None, 'personal_assets', 'users', ['user_id'], ['id'])
    op.drop_column('personal_assets', 'in_someone_name')
    op.add_column('personal_debts', sa.Column('emi_interval_days', sa.Integer(), nullable=True))
    op.add_column('personal_debts', sa.Column('emi_interval_months', sa.Integer(), nullable=True))
    op.add_column('personal_debts', sa.Column('emi_interval_years', sa.Integer(), nullable=True))
    op.alter_column('personal_debts', 'next_interest_increase_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('personal_debts', 'emi_next_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('personal_debts', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('personal_debts', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_column('personal_debts', 'has_installments')
    op.drop_column('personal_debts', 'monthly_emi')
    op.drop_column('personal_debts', 'deducted_from')
    op.drop_column('personal_debts', 'installments_every')
    op.add_column('personal_goal_contributions', sa.Column('note', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'personal_insurances', 'users', ['insured_user_id'], ['id'])
    op.alter_column('recurring_expenses', 'next_payment_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('recurring_incomes', 'next_receiving_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('scheduled_jobs', 'next_retry_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('scheduled_jobs', 'awaiting_since',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_constraint(op.f('scheduled_jobs_source_type_source_id_period_key_key'), 'scheduled_jobs', type_='unique')
    op.alter_column('transfers', 'note',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transfers', 'note',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_unique_constraint(op.f('scheduled_jobs_source_type_source_id_period_key_key'), 'scheduled_jobs', ['source_type', 'source_id', 'period_key'], postgresql_nulls_not_distinct=False)
    op.alter_column('scheduled_jobs', 'awaiting_since',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('scheduled_jobs', 'next_retry_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('recurring_incomes', 'next_receiving_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('recurring_expenses', 'next_payment_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_constraint(None, 'personal_insurances', type_='foreignkey')
    op.drop_column('personal_goal_contributions', 'note')
    op.add_column('personal_debts', sa.Column('installments_every', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('personal_debts', sa.Column('deducted_from', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('personal_debts', sa.Column('monthly_emi', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('personal_debts', sa.Column('has_installments', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('personal_debts', 'end_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('personal_debts', 'start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('personal_debts', 'emi_next_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('personal_debts', 'next_interest_increase_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('personal_debts', 'emi_interval_years')
    op.drop_column('personal_debts', 'emi_interval_months')
    op.drop_column('personal_debts', 'emi_interval_days')
    op.add_column('personal_assets', sa.Column('in_someone_name', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'personal_assets', type_='foreignkey')
    op.create_foreign_key(op.f('personal_assets_in_someone_name_fkey'), 'personal_assets', 'users', ['in_someone_name'], ['id'])
    op.drop_index(op.f('ix_personal_assets_user_id'), table_name='personal_assets')
    op.drop_index(op.f('ix_personal_assets_family_id'), table_name='personal_assets')
    op.alter_column('personal_assets', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('personal_assets', 'user_id')
    op.create_index(op.f('ix_payment_split_plans_entity'), 'payment_split_plans', ['entity_type', 'entity_id'], unique=False)
    op.alter_column('notifications', 'expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('notifications', 'actioned_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_investment_txns_investment_scope'), 'investment_txns', ['investment_scope', 'investment_id'], unique=False)
    op.alter_column('investment_txns', 'note',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_funding_breakdown_entries_job_id'), table_name='funding_breakdown_entries')
    op.drop_index(op.f('ix_funding_breakdown_entries_entity_id'), table_name='funding_breakdown_entries')
    op.create_index(op.f('ix_funding_breakdown_job_id'), 'funding_breakdown_entries', ['job_id'], unique=False)
    op.create_index(op.f('ix_funding_breakdown_entity_id'), 'funding_breakdown_entries', ['entity_id'], unique=False)
    op.drop_constraint(None, 'family_insurances', type_='foreignkey')
    op.drop_column('family_goal_contributions', 'note')
    op.add_column('family_debts', sa.Column('installments_every', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('family_debts', sa.Column('monthly_emi', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('family_debts', sa.Column('has_installments', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('family_debts', 'end_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('family_debts', 'start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('family_debts', 'emi_next_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('family_debts', 'next_interest_increase_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('family_debts', 'emi_interval_years')
    op.drop_column('family_debts', 'emi_interval_months')
    op.drop_column('family_debts', 'emi_interval_days')
    op.drop_index(op.f('ix_family_assets_family_id'), table_name='family_assets')
    op.alter_column('family_assets', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_default_bucket_entries_user_id'), table_name='default_bucket_entries')
    op.drop_index(op.f('ix_default_bucket_entries_family_id'), table_name='default_bucket_entries')
    op.drop_index(op.f('ix_default_bucket_entries_entity_id'), table_name='default_bucket_entries')
    op.create_index(op.f('ix_default_bucket_user_id'), 'default_bucket_entries', ['user_id'], unique=False)
    op.create_index(op.f('ix_default_bucket_family_id'), 'default_bucket_entries', ['family_id'], unique=False)
    op.create_index(op.f('ix_default_bucket_entity_id'), 'default_bucket_entries', ['entity_id'], unique=False)
    op.alter_column('default_bucket_entries', 'settled_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('debts', 'emi_interval_years')
    op.drop_column('debts', 'emi_interval_months')
    op.drop_column('debts', 'emi_interval_days')
    op.create_unique_constraint(op.f('uq_debt_scope_views_target'), 'debt_scope_views', ['debt_id', 'scope_kind', 'family_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_debt_payment_events_period_key'), 'debt_payment_events', ['debt_id', 'period_key'], unique=False)
    op.drop_index(op.f('ix_debt_payment_allocations_payment_event_id'), table_name='debt_payment_allocations')
    op.create_index(op.f('ix_debt_payment_allocations_event_id'), 'debt_payment_allocations', ['payment_event_id'], unique=False)
    op.create_index(op.f('ix_currency_rates_status'), 'currency_rates', ['status'], unique=False)
    op.create_index(op.f('ix_currency_rates_pair'), 'currency_rates', ['base_currency', 'quote_currency'], unique=False)
    op.create_unique_constraint(op.f('bounced_payments_debt_scope_debt_id_period_key_key'), 'bounced_payments', ['debt_scope', 'debt_id', 'period_key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
