"""debt_document_visibility

Revision ID: c34524a8d626
Revises: 77b34f5551ca
Create Date: 2026-07-12 17:22:54.994991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c34524a8d626'
down_revision: Union[str, Sequence[str], None] = '77b34f5551ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debts', sa.Column('show_doc_to_all', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('debts', sa.Column('doc_viewer_user_ids', sa.JSON(), nullable=True))
    op.add_column('family_debts', sa.Column('show_doc_to_all', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('family_debts', sa.Column('doc_viewer_user_ids', sa.JSON(), nullable=True))
    op.add_column('personal_debts', sa.Column('show_doc_to_all', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('personal_debts', sa.Column('doc_viewer_user_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personal_debts', 'doc_viewer_user_ids')
    op.drop_column('personal_debts', 'show_doc_to_all')
    op.drop_column('family_debts', 'doc_viewer_user_ids')
    op.drop_column('family_debts', 'show_doc_to_all')
    op.drop_column('debts', 'doc_viewer_user_ids')
    op.drop_column('debts', 'show_doc_to_all')
    # ### end Alembic commands ###
