"""make token expires_at timezone aware

Revision ID: cfd8aab298a2
Revises: 348a004faf7d
Create Date: 2026-06-22 16:08:05.657118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cfd8aab298a2'
down_revision: Union[str, Sequence[str], None] = '348a004faf7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('family_income_log_access')
    op.drop_table('family_recurring_income_access')
    op.drop_table('exclude_from_family_income_logs')
    op.drop_table('exclude_from_family_recurring_incomes')
    op.alter_column('email_change_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('email_verification_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('family_account_setup_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.add_column('family_income_logs', sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
    op.add_column('family_income_logs', sa.Column('family_amount', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
    op.add_column('family_income_logs', sa.Column('earned_by_user_id', sa.Uuid(), nullable=True))
    op.add_column('family_income_logs', sa.Column('added_by_user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'family_income_logs', 'users', ['earned_by_user_id'], ['id'])
    op.create_foreign_key(None, 'family_income_logs', 'users', ['added_by_user_id'], ['id'])
    op.drop_column('family_income_logs', 'access_level')
    op.drop_column('family_income_logs', 'amount')
    op.add_column('family_recurring_incomes', sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
    op.add_column('family_recurring_incomes', sa.Column('amount_to_be_added_to_family', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
    op.add_column('family_recurring_incomes', sa.Column('added_by_user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'family_recurring_incomes', 'users', ['added_by_user_id'], ['id'])
    op.drop_column('family_recurring_incomes', 'access_level')
    op.drop_column('family_recurring_incomes', 'amount')
    op.alter_column('forget_password_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('reset_password_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reset_password_tokens', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('forget_password_tokens', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.add_column('family_recurring_incomes', sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('family_recurring_incomes', sa.Column('access_level', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'family_recurring_incomes', type_='foreignkey')
    op.drop_column('family_recurring_incomes', 'added_by_user_id')
    op.drop_column('family_recurring_incomes', 'amount_to_be_added_to_family')
    op.drop_column('family_recurring_incomes', 'total_amount')
    op.add_column('family_income_logs', sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('family_income_logs', sa.Column('access_level', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'family_income_logs', type_='foreignkey')
    op.drop_constraint(None, 'family_income_logs', type_='foreignkey')
    op.drop_column('family_income_logs', 'added_by_user_id')
    op.drop_column('family_income_logs', 'earned_by_user_id')
    op.drop_column('family_income_logs', 'family_amount')
    op.drop_column('family_income_logs', 'total_amount')
    op.alter_column('family_account_setup_tokens', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('email_verification_tokens', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('email_change_tokens', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.create_table('exclude_from_family_recurring_incomes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('income_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['income_id'], ['family_recurring_incomes.id'], name=op.f('exclude_from_family_recurring_incomes_income_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('exclude_from_family_recurring_incomes_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('exclude_from_family_recurring_incomes_pkey'))
    )
    op.create_table('exclude_from_family_income_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('income_log_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['income_log_id'], ['family_income_logs.id'], name=op.f('exclude_from_family_income_logs_income_log_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('exclude_from_family_income_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('exclude_from_family_income_logs_pkey'))
    )
    op.create_table('family_recurring_income_access',
    sa.Column('income_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('access_level', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['income_id'], ['family_recurring_incomes.id'], name=op.f('family_recurring_income_access_income_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('family_recurring_income_access_user_id_fkey')),
    sa.PrimaryKeyConstraint('income_id', 'user_id', name=op.f('family_recurring_income_access_pkey'))
    )
    op.create_table('family_income_log_access',
    sa.Column('income_log_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('access_level', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['income_log_id'], ['family_income_logs.id'], name=op.f('family_income_log_access_income_log_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('family_income_log_access_user_id_fkey')),
    sa.PrimaryKeyConstraint('income_log_id', 'user_id', name=op.f('family_income_log_access_pkey'))
    )
    # ### end Alembic commands ###
