"""added auth, family and user models

Revision ID: d345b25b8345
Revises: b617848db647
Create Date: 2026-06-20 07:12:34.704808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd345b25b8345'
down_revision: Union[str, Sequence[str], None] = 'b617848db647'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_change_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('new_email', sa.String(), nullable=False),
    sa.Column('otp_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_change_tokens_id'), 'email_change_tokens', ['id'], unique=True)
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_email_verification_tokens_id'), 'email_verification_tokens', ['id'], unique=True)
    op.create_table('family_goals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('goal_name', sa.String(), nullable=False),
    sa.Column('goal_type', sa.String(), nullable=True),
    sa.Column('target_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('collected_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.Column('contribution_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('contribution_every', sa.String(), nullable=True),
    sa.Column('next_contribution_date', sa.DateTime(), nullable=True),
    sa.Column('auto_deduct', sa.Boolean(), nullable=False),
    sa.Column('funded_from', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('access_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_goals_family_id'), 'family_goals', ['family_id'], unique=False)
    op.create_table('family_income_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('logged_by', sa.Uuid(), nullable=False),
    sa.Column('income_name', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('income_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('personal_savings_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('personal_savings_user_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('access_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['logged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['personal_savings_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_income_logs_family_id'), 'family_income_logs', ['family_id'], unique=False)
    op.create_table('family_insurances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('insurance_name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('policy_number', sa.String(), nullable=True),
    sa.Column('insured_member', sa.Uuid(), nullable=True),
    sa.Column('nominee', sa.String(), nullable=True),
    sa.Column('coverage_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('premium_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('premium_every', sa.String(), nullable=True),
    sa.Column('next_premium_date', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('maturity_date', sa.DateTime(), nullable=True),
    sa.Column('maturity_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('access_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['insured_member'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_insurances_family_id'), 'family_insurances', ['family_id'], unique=False)
    op.create_table('family_recurring_incomes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('income_name', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('received_every', sa.String(), nullable=True),
    sa.Column('next_receiving_date', sa.DateTime(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('personal_savings_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('personal_savings_user_id', sa.Uuid(), nullable=True),
    sa.Column('access_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['personal_savings_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_recurring_incomes_family_id'), 'family_recurring_incomes', ['family_id'], unique=False)
    op.create_table('family_savings_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('plan_name', sa.String(), nullable=False),
    sa.Column('purpose_type', sa.String(), nullable=False),
    sa.Column('linked_type', sa.String(), nullable=True),
    sa.Column('linked_id', sa.Uuid(), nullable=True),
    sa.Column('target_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('accumulated_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('target_frequency', sa.String(), nullable=True),
    sa.Column('next_target_date', sa.DateTime(), nullable=True),
    sa.Column('contribution_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('contribution_every', sa.String(), nullable=False),
    sa.Column('next_contribution_date', sa.DateTime(), nullable=True),
    sa.Column('auto_deduct', sa.Boolean(), nullable=False),
    sa.Column('deduct_at_period_start', sa.Boolean(), nullable=False),
    sa.Column('funded_from', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('access_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_savings_plans_family_id'), 'family_savings_plans', ['family_id'], unique=False)
    op.create_table('family_total_savings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('total_savings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id')
    )
    op.create_table('forget_password_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_forget_password_tokens_id'), 'forget_password_tokens', ['id'], unique=True)
    op.create_table('personal_goals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('goal_name', sa.String(), nullable=False),
    sa.Column('goal_type', sa.String(), nullable=True),
    sa.Column('target_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('collected_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.Column('contribution_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('contribution_every', sa.String(), nullable=True),
    sa.Column('next_contribution_date', sa.DateTime(), nullable=True),
    sa.Column('auto_deduct', sa.Boolean(), nullable=False),
    sa.Column('funded_from', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('access_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_goals_family_id'), 'personal_goals', ['family_id'], unique=False)
    op.create_table('personal_income_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('logged_by', sa.Uuid(), nullable=False),
    sa.Column('income_name', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('income_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('personal_savings_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('access_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['logged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_income_logs_family_id'), 'personal_income_logs', ['family_id'], unique=False)
    op.create_table('personal_insurances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('insurance_name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('policy_number', sa.String(), nullable=True),
    sa.Column('insured_member', sa.Uuid(), nullable=True),
    sa.Column('nominee', sa.String(), nullable=True),
    sa.Column('coverage_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('premium_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('premium_every', sa.String(), nullable=True),
    sa.Column('next_premium_date', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('maturity_date', sa.DateTime(), nullable=True),
    sa.Column('maturity_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('deducted_from', sa.String(), nullable=True),
    sa.Column('access_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['insured_member'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_insurances_family_id'), 'personal_insurances', ['family_id'], unique=False)
    op.create_table('personal_recurring_incomes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('income_name', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('received_every', sa.String(), nullable=True),
    sa.Column('next_receiving_date', sa.DateTime(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('deducted_from', sa.String(), nullable=True),
    sa.Column('access_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_recurring_incomes_family_id'), 'personal_recurring_incomes', ['family_id'], unique=False)
    op.create_table('personal_savings_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('access_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_savings_logs_family_id'), 'personal_savings_logs', ['family_id'], unique=False)
    op.create_table('personal_savings_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan_name', sa.String(), nullable=False),
    sa.Column('purpose_type', sa.String(), nullable=False),
    sa.Column('linked_type', sa.String(), nullable=True),
    sa.Column('linked_id', sa.Uuid(), nullable=True),
    sa.Column('target_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('accumulated_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('target_frequency', sa.String(), nullable=True),
    sa.Column('next_target_date', sa.DateTime(), nullable=True),
    sa.Column('contribution_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('contribution_every', sa.String(), nullable=False),
    sa.Column('next_contribution_date', sa.DateTime(), nullable=True),
    sa.Column('auto_deduct', sa.Boolean(), nullable=False),
    sa.Column('deduct_at_period_start', sa.Boolean(), nullable=False),
    sa.Column('funded_from', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('access_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_savings_plans_family_id'), 'personal_savings_plans', ['family_id'], unique=False)
    op.create_table('personal_total_savings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('total_savings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('token_family_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=True)
    op.create_table('reset_password_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_reset_password_tokens_id'), 'reset_password_tokens', ['id'], unique=True)
    op.create_table('exclude_from_family_goals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['family_goals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exclude_from_family_income_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('income_log_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['income_log_id'], ['family_income_logs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exclude_from_family_insurances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('insurance_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['insurance_id'], ['family_insurances.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exclude_from_family_recurring_incomes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('income_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['income_id'], ['family_recurring_incomes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exclude_from_family_savings_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['family_savings_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_goal_access',
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('access_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['family_goals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('goal_id', 'user_id')
    )
    op.create_table('family_goal_contributions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('contributed_by', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('contribution_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contributed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['family_goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_goal_contributions_family_id'), 'family_goal_contributions', ['family_id'], unique=False)
    op.create_index(op.f('ix_family_goal_contributions_goal_id'), 'family_goal_contributions', ['goal_id'], unique=False)
    op.create_table('family_income_log_access',
    sa.Column('income_log_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('access_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['income_log_id'], ['family_income_logs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('income_log_id', 'user_id')
    )
    op.create_table('family_insurance_access',
    sa.Column('insurance_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('access_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['insurance_id'], ['family_insurances.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('insurance_id', 'user_id')
    )
    op.create_table('family_recurring_income_access',
    sa.Column('income_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('access_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['income_id'], ['family_recurring_incomes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('income_id', 'user_id')
    )
    op.create_table('family_savings_plan_access',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('access_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['family_savings_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('plan_id', 'user_id')
    )
    op.create_table('family_savings_plan_contributions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('contributed_by', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('contribution_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contributed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['family_savings_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_savings_plan_contributions_family_id'), 'family_savings_plan_contributions', ['family_id'], unique=False)
    op.create_index(op.f('ix_family_savings_plan_contributions_plan_id'), 'family_savings_plan_contributions', ['plan_id'], unique=False)
    op.create_table('personal_goal_access',
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('access_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['personal_goals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('goal_id', 'user_id')
    )
    op.create_table('personal_goal_contributions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('contribution_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['personal_goals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_goal_contributions_family_id'), 'personal_goal_contributions', ['family_id'], unique=False)
    op.create_index(op.f('ix_personal_goal_contributions_goal_id'), 'personal_goal_contributions', ['goal_id'], unique=False)
    op.create_table('personal_income_log_access',
    sa.Column('income_log_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('access_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['income_log_id'], ['personal_income_logs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('income_log_id', 'user_id')
    )
    op.create_table('personal_insurance_access',
    sa.Column('insurance_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('access_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['insurance_id'], ['personal_insurances.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('insurance_id', 'user_id')
    )
    op.create_table('personal_recurring_income_access',
    sa.Column('income_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('access_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['income_id'], ['personal_recurring_incomes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('income_id', 'user_id')
    )
    op.create_table('personal_savings_logs_access',
    sa.Column('savings_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('access_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['savings_id'], ['personal_savings_logs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('savings_id', 'user_id')
    )
    op.create_table('personal_savings_plan_access',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('access_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['personal_savings_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('plan_id', 'user_id')
    )
    op.create_table('personal_savings_plan_contributions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('contribution_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['personal_savings_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_savings_plan_contributions_family_id'), 'personal_savings_plan_contributions', ['family_id'], unique=False)
    op.create_index(op.f('ix_personal_savings_plan_contributions_plan_id'), 'personal_savings_plan_contributions', ['plan_id'], unique=False)
    op.drop_table('personal_savings_access')
    op.drop_table('family_income_access')
    op.drop_index(op.f('ix_personal_savings_family_id'), table_name='personal_savings')
    op.drop_table('personal_savings')
    op.drop_index(op.f('ix_family_incomes_family_id'), table_name='family_incomes')
    op.drop_table('family_incomes')
    op.add_column('family_debts', sa.Column('interest_increase_every', sa.String(), nullable=True))
    op.add_column('family_debts', sa.Column('interest_increase_percentage', sa.Float(), nullable=True))
    op.add_column('family_debts', sa.Column('next_interest_increase_date', sa.DateTime(), nullable=True))
    op.drop_column('family_debts', 'intrest_increase_percentage')
    op.drop_column('family_debts', 'next_intreast_increase_date')
    op.drop_column('family_debts', 'intrest_increase_every')
    op.add_column('personal_assets', sa.Column('deducted_from', sa.String(), nullable=True))
    op.add_column('personal_debts', sa.Column('interest_increase_every', sa.String(), nullable=True))
    op.add_column('personal_debts', sa.Column('interest_increase_percentage', sa.Float(), nullable=True))
    op.add_column('personal_debts', sa.Column('next_interest_increase_date', sa.DateTime(), nullable=True))
    op.add_column('personal_debts', sa.Column('deducted_from', sa.String(), nullable=True))
    op.drop_column('personal_debts', 'intrest_increase_percentage')
    op.drop_column('personal_debts', 'next_intreast_increase_date')
    op.drop_column('personal_debts', 'intrest_increase_every')
    op.add_column('personal_expenses', sa.Column('deducted_from', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_email_verified')
    op.drop_column('personal_expenses', 'deducted_from')
    op.add_column('personal_debts', sa.Column('intrest_increase_every', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('personal_debts', sa.Column('next_intreast_increase_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('personal_debts', sa.Column('intrest_increase_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('personal_debts', 'deducted_from')
    op.drop_column('personal_debts', 'next_interest_increase_date')
    op.drop_column('personal_debts', 'interest_increase_percentage')
    op.drop_column('personal_debts', 'interest_increase_every')
    op.drop_column('personal_assets', 'deducted_from')
    op.add_column('family_debts', sa.Column('intrest_increase_every', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('family_debts', sa.Column('next_intreast_increase_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('family_debts', sa.Column('intrest_increase_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('family_debts', 'next_interest_increase_date')
    op.drop_column('family_debts', 'interest_increase_percentage')
    op.drop_column('family_debts', 'interest_increase_every')
    op.create_table('family_incomes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('family_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('income_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('is_recurring', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('received_every', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('next_receiving_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('personal_savings_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('access_level', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('family_incomes_document_id_fkey')),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('family_incomes_family_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('family_incomes_pkey'))
    )
    op.create_index(op.f('ix_family_incomes_family_id'), 'family_incomes', ['family_id'], unique=False)
    op.create_table('personal_savings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('family_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('access_level', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('personal_savings_document_id_fkey')),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('personal_savings_family_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('personal_savings_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('personal_savings_pkey'))
    )
    op.create_index(op.f('ix_personal_savings_family_id'), 'personal_savings', ['family_id'], unique=False)
    op.create_table('family_income_access',
    sa.Column('income_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('access_level', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['income_id'], ['family_incomes.id'], name=op.f('family_income_access_income_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('family_income_access_user_id_fkey')),
    sa.PrimaryKeyConstraint('income_id', 'user_id', name=op.f('family_income_access_pkey'))
    )
    op.create_table('personal_savings_access',
    sa.Column('savings_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('access_level', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['savings_id'], ['personal_savings.id'], name=op.f('personal_savings_access_savings_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('personal_savings_access_user_id_fkey')),
    sa.PrimaryKeyConstraint('savings_id', 'user_id', name=op.f('personal_savings_access_pkey'))
    )
    op.drop_index(op.f('ix_personal_savings_plan_contributions_plan_id'), table_name='personal_savings_plan_contributions')
    op.drop_index(op.f('ix_personal_savings_plan_contributions_family_id'), table_name='personal_savings_plan_contributions')
    op.drop_table('personal_savings_plan_contributions')
    op.drop_table('personal_savings_plan_access')
    op.drop_table('personal_savings_logs_access')
    op.drop_table('personal_recurring_income_access')
    op.drop_table('personal_insurance_access')
    op.drop_table('personal_income_log_access')
    op.drop_index(op.f('ix_personal_goal_contributions_goal_id'), table_name='personal_goal_contributions')
    op.drop_index(op.f('ix_personal_goal_contributions_family_id'), table_name='personal_goal_contributions')
    op.drop_table('personal_goal_contributions')
    op.drop_table('personal_goal_access')
    op.drop_index(op.f('ix_family_savings_plan_contributions_plan_id'), table_name='family_savings_plan_contributions')
    op.drop_index(op.f('ix_family_savings_plan_contributions_family_id'), table_name='family_savings_plan_contributions')
    op.drop_table('family_savings_plan_contributions')
    op.drop_table('family_savings_plan_access')
    op.drop_table('family_recurring_income_access')
    op.drop_table('family_insurance_access')
    op.drop_table('family_income_log_access')
    op.drop_index(op.f('ix_family_goal_contributions_goal_id'), table_name='family_goal_contributions')
    op.drop_index(op.f('ix_family_goal_contributions_family_id'), table_name='family_goal_contributions')
    op.drop_table('family_goal_contributions')
    op.drop_table('family_goal_access')
    op.drop_table('exclude_from_family_savings_plans')
    op.drop_table('exclude_from_family_recurring_incomes')
    op.drop_table('exclude_from_family_insurances')
    op.drop_table('exclude_from_family_income_logs')
    op.drop_table('exclude_from_family_goals')
    op.drop_index(op.f('ix_reset_password_tokens_id'), table_name='reset_password_tokens')
    op.drop_table('reset_password_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('personal_total_savings')
    op.drop_index(op.f('ix_personal_savings_plans_family_id'), table_name='personal_savings_plans')
    op.drop_table('personal_savings_plans')
    op.drop_index(op.f('ix_personal_savings_logs_family_id'), table_name='personal_savings_logs')
    op.drop_table('personal_savings_logs')
    op.drop_index(op.f('ix_personal_recurring_incomes_family_id'), table_name='personal_recurring_incomes')
    op.drop_table('personal_recurring_incomes')
    op.drop_index(op.f('ix_personal_insurances_family_id'), table_name='personal_insurances')
    op.drop_table('personal_insurances')
    op.drop_index(op.f('ix_personal_income_logs_family_id'), table_name='personal_income_logs')
    op.drop_table('personal_income_logs')
    op.drop_index(op.f('ix_personal_goals_family_id'), table_name='personal_goals')
    op.drop_table('personal_goals')
    op.drop_index(op.f('ix_forget_password_tokens_id'), table_name='forget_password_tokens')
    op.drop_table('forget_password_tokens')
    op.drop_table('family_total_savings')
    op.drop_index(op.f('ix_family_savings_plans_family_id'), table_name='family_savings_plans')
    op.drop_table('family_savings_plans')
    op.drop_index(op.f('ix_family_recurring_incomes_family_id'), table_name='family_recurring_incomes')
    op.drop_table('family_recurring_incomes')
    op.drop_index(op.f('ix_family_insurances_family_id'), table_name='family_insurances')
    op.drop_table('family_insurances')
    op.drop_index(op.f('ix_family_income_logs_family_id'), table_name='family_income_logs')
    op.drop_table('family_income_logs')
    op.drop_index(op.f('ix_family_goals_family_id'), table_name='family_goals')
    op.drop_table('family_goals')
    op.drop_index(op.f('ix_email_verification_tokens_id'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    op.drop_index(op.f('ix_email_change_tokens_id'), table_name='email_change_tokens')
    op.drop_table('email_change_tokens')
    # ### end Alembic commands ###
