"""added model for invite tokes and account setup

Revision ID: dd752693c0d8
Revises: d345b25b8345
Create Date: 2026-06-20 12:14:37.720819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'dd752693c0d8'
down_revision: Union[str, Sequence[str], None] = 'd345b25b8345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_account_setup_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('invited_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_family_account_setup_tokens_id'), 'family_account_setup_tokens', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_family_account_setup_tokens_id'), table_name='family_account_setup_tokens')
    op.drop_table('family_account_setup_tokens')
    # ### end Alembic commands ###
