"""comment

Revision ID: ddd810043e76
Revises: 9d5ee528c629
Create Date: 2026-06-23 17:53:33.854570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddd810043e76'
down_revision: Union[str, Sequence[str], None] = '9d5ee528c629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family_income_logs', sa.Column('show_doc_to_all', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('family_recurring_incomes', sa.Column('show_docs_to_all', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('family_recurring_incomes', sa.Column('repeat_doc_with_logs', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('personal_income_logs', sa.Column('show_doc_to_all', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('personal_recurring_incomes', sa.Column('show_docs_to_all', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('personal_recurring_incomes', sa.Column('repeat_doc_with_logs', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personal_recurring_incomes', 'repeat_doc_with_logs')
    op.drop_column('personal_recurring_incomes', 'show_docs_to_all')
    op.drop_column('personal_income_logs', 'show_doc_to_all')
    op.drop_column('family_recurring_incomes', 'repeat_doc_with_logs')
    op.drop_column('family_recurring_incomes', 'show_docs_to_all')
    op.drop_column('family_income_logs', 'show_doc_to_all')
    # ### end Alembic commands ###
