"""Family System V2 string enums (stored as VARCHAR + app validation)."""

SCOPE_FAMILY = "FAMILY"

ACCESS_PRIVATE = "PRIVATE"
ACCESS_FAMILY = "FAMILY"
ACCESS_SELECTED = "SELECTED"

ROLE_MANAGER = "MANAGER"
ROLE_MEMBER = "MEMBER"

VISIBILITY_FAMILY = "FAMILY"
VISIBILITY_MEMBERS_ONLY = "MEMBERS_ONLY"

POOL_FAMILY = "FAMILY"
# Single user-level personal account (not per-family).
POOL_PERSONAL = "PERSONAL"

LEDGER_IN = "IN"
LEDGER_OUT = "OUT"

LEDGER_SOURCE_ORIGIN = "ORIGIN"
LEDGER_SOURCE_MANUAL = "MANUAL"
LEDGER_SOURCE_INCOME_LOG = "INCOME_LOG"
LEDGER_SOURCE_RECURRING_INCOME = "RECURRING_INCOME"
LEDGER_SOURCE_TRANSFER = "TRANSFER"
LEDGER_SOURCE_EMI = "EMI"
LEDGER_SOURCE_EXPENSE_LOG = "EXPENSE_LOG"
LEDGER_SOURCE_RECURRING_EXPENSE = "RECURRING_EXPENSE"
LEDGER_SOURCE_CONTRIBUTION = "CONTRIBUTION"

SOURCE_LINKED_INCOME_LOG = "LINKED_INCOME_LOG"
SOURCE_LINKED_EXPENSE_LOG = "LINKED_EXPENSE_LOG"
LEDGER_SOURCE_ADJUSTMENT = "ADJUSTMENT"
LEDGER_SOURCE_INSURANCE_PREMIUM = "INSURANCE_PREMIUM"
LEDGER_SOURCE_ASSET_EMI = "ASSET_EMI"
LEDGER_SOURCE_GLOBAL_ENTRY = "GLOBAL_ENTRY"

# New ledger sources (Plan 01)
LEDGER_SOURCE_DEBT_EMI = "DEBT_EMI"
LEDGER_SOURCE_DEBT_PART_PAYMENT = "DEBT_PART_PAYMENT"
LEDGER_SOURCE_DEFAULT_SETTLEMENT = "DEFAULT_SETTLEMENT"
LEDGER_SOURCE_INVESTMENT_CONTRIB = "INVESTMENT_CONTRIB"
LEDGER_SOURCE_INVESTMENT_MATURITY = "INVESTMENT_MATURITY"
LEDGER_SOURCE_SAVINGS_PLAN = "SAVINGS_PLAN"
LEDGER_SOURCE_GOAL_CONTRIB = "GOAL_CONTRIB"

# Funding "external" marker for PAID_EXTERNALLY logs
FUNDING_EXTERNAL = "EXTERNAL"

# Transfer
TRANSFER_ENTITY_SAVINGS = "SAVINGS"
TRANSFER_STATUS_PENDING = "PENDING"
TRANSFER_STATUS_ACTIVE = "ACTIVE"
TRANSFER_STATUS_COMPLETED = "COMPLETED"
TRANSFER_STATUS_CANCELLED = "CANCELLED"

# Shares
SHARE_STATUS_ACTIVE = "ACTIVE"
SHARE_STATUS_REVOKED = "REVOKED"

# Jobs
JOB_STATUS_SCHEDULED = "SCHEDULED"
JOB_STATUS_AWAITING_CONFIRMATION = "AWAITING_CONFIRMATION"
JOB_STATUS_APPLIED = "APPLIED"
JOB_STATUS_DELAYED = "DELAYED"
JOB_STATUS_SKIPPED = "SKIPPED"
JOB_STATUS_CANCELLED = "CANCELLED"
JOB_STATUS_FAILED = "FAILED"

JOB_TYPE_RECURRING_INCOME = "RECURRING_INCOME"
JOB_TYPE_RECURRING_EXPENSE = "RECURRING_EXPENSE"
JOB_TYPE_DEBT_EMI = "DEBT_EMI"
JOB_TYPE_GOAL_CONTRIB = "GOAL_CONTRIB"
JOB_TYPE_SAVINGS_PLAN_CONTRIB = "SAVINGS_PLAN_CONTRIB"
JOB_TYPE_ASSET_EMI = "ASSET_EMI"
JOB_TYPE_ASSET_VALUE_INCREASE = "ASSET_VALUE_INCREASE"
JOB_TYPE_INSURANCE_PREMIUM = "INSURANCE_PREMIUM"
JOB_TYPE_DEBT_INTEREST_INCREASE = "DEBT_INTEREST_INCREASE"
JOB_TYPE_AUTO_TRANSFER = "AUTO_TRANSFER"

# New job types (Plan 01 / Plan 04)
JOB_TYPE_INVESTMENT_CONTRIB = "INVESTMENT_CONTRIB"
JOB_TYPE_INVESTMENT_MATURITY = "INVESTMENT_MATURITY"

# Notifications
NOTIF_STATUS_UNREAD = "UNREAD"
NOTIF_STATUS_READ = "READ"
NOTIF_STATUS_ACTIONED = "ACTIONED"
NOTIF_STATUS_DISMISSED = "DISMISSED"

ACTION_ACCEPT = "ACCEPT"
ACTION_DECLINE_DELAY = "DECLINE_DELAY"
ACTION_SKIP_PERIOD = "SKIP_PERIOD"
ACTION_SKIP_DEFAULT = "SKIP_DEFAULT"
ACTION_SKIP_INCREASE = "SKIP_INCREASE"
ACTION_REMOVE_SOURCE = "REMOVE_SOURCE"
ACTION_REMOVE_RECURRING = "REMOVE_RECURRING"
ACTION_DISMISS = "DISMISS"
ACTION_AUTO_ACCEPTED = "AUTO_ACCEPTED"

# New notification actions (Plan 01)
ACTION_PAID_EXTERNALLY = "PAID_EXTERNALLY"       # mark period done, advance date, NO pool deduction; log with EXTERNAL funding
ACTION_ACCEPT_WITH_SPLITS = "ACCEPT_WITH_SPLITS" # accept with user-provided one-off split override
ACTION_ADJUST_AMOUNT = "ADJUST_AMOUNT"            # accept with a changed amount

# EMI / sinking-fund recompute modes
EMI_MODE_FIXED = "FIXED"
EMI_MODE_AUTO_RECOMPUTE = "AUTO_RECOMPUTE"

# Prepay / early-add recompute options
PREPAY_MODE_CLEAR_UPCOMING = "CLEAR_UPCOMING"
PREPAY_MODE_REDUCE_EMI = "REDUCE_EMI"
PREPAY_MODE_KEEP_EMI_REDUCE_TENURE = "KEEP_EMI_REDUCE_TENURE"

# Pool types for split lines (Plan 01)
SPLIT_POOL_CURRENT_FAMILY = "CURRENT_FAMILY"
SPLIT_POOL_PERSONAL = "PERSONAL"
SPLIT_POOL_OTHER_FAMILY = "OTHER_FAMILY"

# Entity types for split plans / breakdown / default buckets (Plan 01)
ENTITY_FAMILY_DEBT = "FAMILY_DEBT"
ENTITY_PERSONAL_DEBT = "PERSONAL_DEBT"
ENTITY_FAMILY_INVESTMENT = "FAMILY_INVESTMENT"
ENTITY_PERSONAL_INVESTMENT = "PERSONAL_INVESTMENT"
ENTITY_FAMILY_INSURANCE = "FAMILY_INSURANCE"
ENTITY_PERSONAL_INSURANCE = "PERSONAL_INSURANCE"
ENTITY_FAMILY_SAVINGS_PLAN = "FAMILY_SAVINGS_PLAN"
ENTITY_PERSONAL_SAVINGS_PLAN = "PERSONAL_SAVINGS_PLAN"
ENTITY_TRANSFER = "TRANSFER"
ENTITY_FAMILY_EXPENSE_LOG = "FAMILY_EXPENSE_LOG"
ENTITY_PERSONAL_EXPENSE_LOG = "PERSONAL_EXPENSE_LOG"

# Bounced
BOUNCE_STATUS_BOUNCED = "BOUNCED"
BOUNCE_STATUS_PAID_LATE = "PAID_LATE"
BOUNCE_STATUS_WAIVED = "WAIVED"

# Default bucket (Plan 01)
DEFAULT_BUCKET_STATUS_OPEN = "OPEN"
DEFAULT_BUCKET_STATUS_SETTLED = "SETTLED"
DEFAULT_BUCKET_STATUS_WAIVED = "WAIVED"
DEFAULT_BUCKET_REASON_BOUNCED = "BOUNCED"
DEFAULT_BUCKET_REASON_SKIPPED_TO_DEFAULT = "SKIPPED_TO_DEFAULT"


# Job / debt source types (Plan 01 Phase 1 consolidation)
SOURCE_DEBT = "DEBT"


def allowed_actions_for_job_type(job_type: str) -> list[str]:
    """Notification actions offered for a job, given its type.

    EMI / sinking-fund style jobs (savings-plan & goal contributions, debt EMIs)
    additionally offer SKIP_DEFAULT (skip, keep amount) and SKIP_INCREASE (skip,
    raise future amounts to compensate).
    """
    base = [ACTION_ACCEPT, ACTION_DECLINE_DELAY]
    emi_types = {
        JOB_TYPE_SAVINGS_PLAN_CONTRIB,
        JOB_TYPE_GOAL_CONTRIB,
        JOB_TYPE_DEBT_EMI,
        JOB_TYPE_INVESTMENT_CONTRIB,
    }
    if job_type in emi_types:
        return base + [
            ACTION_ACCEPT_WITH_SPLITS,
            ACTION_ADJUST_AMOUNT,
            ACTION_PAID_EXTERNALLY,
            ACTION_SKIP_DEFAULT,
            ACTION_SKIP_INCREASE,
            ACTION_REMOVE_RECURRING,
            ACTION_DISMISS,
        ]
    recurring_types = {
        JOB_TYPE_RECURRING_INCOME,
        JOB_TYPE_RECURRING_EXPENSE,
        JOB_TYPE_INSURANCE_PREMIUM,
        JOB_TYPE_AUTO_TRANSFER,
    }
    if job_type in recurring_types:
        return base + [
            ACTION_ACCEPT_WITH_SPLITS,
            ACTION_ADJUST_AMOUNT,
            ACTION_PAID_EXTERNALLY,
            ACTION_SKIP_PERIOD,
            ACTION_REMOVE_RECURRING,
            ACTION_DISMISS,
        ]
    return base + [ACTION_SKIP_PERIOD, ACTION_REMOVE_RECURRING, ACTION_DISMISS]
